# Generated by Django 3.1.3 on 2020-11-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='userid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
